// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfwGYbUS9VLVLctZSbxmVxyJaN-AjVldM',
    appId: '1:47234836438:web:00238faef13ac2d680e677',
    messagingSenderId: '47234836438',
    projectId: 'taskmanager2-9e0a9',
    authDomain: 'taskmanager2-9e0a9.firebaseapp.com',
    databaseURL: 'https://taskmanager2-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager2-9e0a9.appspot.com',
    measurementId: 'G-89D3EM46Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjEbtspzocF5lR7Yng9QoDpJJrdRqAy1E',
    appId: '1:47234836438:android:a2592eefdb773fbe80e677',
    messagingSenderId: '47234836438',
    projectId: 'taskmanager2-9e0a9',
    databaseURL: 'https://taskmanager2-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager2-9e0a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiO5xSaYQIEkOeDH9u-kSFso3Zv2NCUl8',
    appId: '1:47234836438:ios:9618d0109a98d2b380e677',
    messagingSenderId: '47234836438',
    projectId: 'taskmanager2-9e0a9',
    databaseURL: 'https://taskmanager2-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager2-9e0a9.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiO5xSaYQIEkOeDH9u-kSFso3Zv2NCUl8',
    appId: '1:47234836438:ios:9618d0109a98d2b380e677',
    messagingSenderId: '47234836438',
    projectId: 'taskmanager2-9e0a9',
    databaseURL: 'https://taskmanager2-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager2-9e0a9.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfwGYbUS9VLVLctZSbxmVxyJaN-AjVldM',
    appId: '1:47234836438:web:5322603071c89e1b80e677',
    messagingSenderId: '47234836438',
    projectId: 'taskmanager2-9e0a9',
    authDomain: 'taskmanager2-9e0a9.firebaseapp.com',
    databaseURL: 'https://taskmanager2-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager2-9e0a9.appspot.com',
    measurementId: 'G-W7JKS4QLLB',
  );
}
